package pl.edu.pwr.lab12;

import com.formdev.flatlaf.FlatDarkLaf;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.script.ScriptException;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.FileSystems;
import java.util.stream.Stream;

public class MainFrame extends JFrame {
    private JButton startButton;
    private JButton stopButton;
    private JComboBox<String> scriptSelector;
    private final DefaultComboBoxModel<String> scriptSelectorModel = new DefaultComboBoxModel<>();
    private JButton reloadFilesButton;
    private JPanel canvasContainer;
    private JPanel mainPanel;
    private JSpinner simulationSpeed;

    private final Canvas canvas;

    private final Dimension CANVAS_SIZE = new Dimension(800, 600);
    private final Dimension RESOLUTION = new Dimension(16, 16);

    private JavascriptLoader loader;

    private boolean isSimRunning = false;


    public MainFrame() {
        super("");
        canvasContainer.setPreferredSize(new Dimension(CANVAS_SIZE.width + 1, CANVAS_SIZE.height + 1));
        canvasContainer.setMaximumSize(new Dimension(CANVAS_SIZE.width + 1, CANVAS_SIZE.height + 1));
        canvas = new Canvas(RESOLUTION);
        canvas.setSize(CANVAS_SIZE);
        canvasContainer.add(canvas);
        simulationSpeed.setValue(100);

        scriptSelector.setModel(scriptSelectorModel);
        scriptSelector.addActionListener(e -> handleSelectionChanged());

        setContentPane(mainPanel);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
        setVisible(true);
        setResizable(false);

        startButton.addActionListener(e -> handleStart());
        stopButton.addActionListener(e -> handleStop());
        reloadFilesButton.addActionListener(e -> findJsFiles());

        findJsFiles();
        var size = canvas.getDataSize();
        var data = new int[size.width][size.height];
        canvas.setData(data);


    }

    private void handleSelectionChanged() {
        var selectedItem = scriptSelector.getSelectedItem();
        if (selectedItem == null || selectedItem.equals("")) return;
        startButton.setEnabled(true);
    }

    private void findJsFiles() {
        scriptSelectorModel.removeAllElements();
        var fileList = FileSystems.getDefault().getPath(".").toFile().listFiles();
        if (fileList == null) return;
        Stream.of(fileList)
                .filter(file -> !file.isDirectory() && file.getName().matches("^.*\\.js$"))
                .map(File::getName)
                .forEach(scriptSelectorModel::addElement);
    }

    private void handleStart() {
        if (isSimRunning) return;
        isSimRunning = true;
        startSimulation();
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
        scriptSelector.setEnabled(false);
    }

    private void handleStop() {
        isSimRunning = false;
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
        scriptSelector.setEnabled(true);
    }

    private void startSimulation() {
        try {
            var selectedItem = scriptSelector.getSelectedItem();
            if (selectedItem == null || selectedItem.equals("")) return;
            loader = new JavascriptLoader((String) selectedItem);
            new Thread(() -> {
                while (isSimRunning) {
                    var currGeneration = canvas.getData();
                    int[][] nextGen;
                    try {
                        nextGen = loader.nextGeneration(currGeneration);
                        canvas.setData(nextGen);
                    } catch (ScriptException | NoSuchMethodException e) {
                        SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Could not continue simulation, error unknown", "Error", JOptionPane.ERROR_MESSAGE));

                    }
                    try {
                        Thread.sleep(Integer.toUnsignedLong((Integer) simulationSpeed.getValue()));
                    } catch (InterruptedException ignored) {
                        Thread.currentThread().interrupt();
                    }
                }
                System.out.println("Simulation thead finished");
            }).start();
        } catch (FileNotFoundException | NoSuchMethodException | ScriptException e) {
            throw new RuntimeException(e);
        }

    }

    public static void main(String[] args) {
        FlatDarkLaf.setup();
        new MainFrame();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 6, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        startButton = new JButton();
        startButton.setEnabled(false);
        startButton.setText("Start");
        mainPanel.add(startButton, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        canvasContainer = new JPanel();
        canvasContainer.setLayout(new CardLayout(0, 0));
        canvasContainer.setBackground(new Color(-14605013));
        canvasContainer.setEnabled(true);
        mainPanel.add(canvasContainer, new GridConstraints(0, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scriptSelector = new JComboBox();
        mainPanel.add(scriptSelector, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Load JS file");
        mainPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        reloadFilesButton = new JButton();
        reloadFilesButton.setText("Reload files");
        mainPanel.add(reloadFilesButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stopButton = new JButton();
        stopButton.setEnabled(false);
        stopButton.setText("Stop");
        mainPanel.add(stopButton, new GridConstraints(2, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 2, 2, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Simulation speed (ms)");
        panel1.add(label2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        simulationSpeed = new JSpinner();
        panel1.add(simulationSpeed, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label2.setLabelFor(simulationSpeed);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
