/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_edu_pwr_lab11_Sorting */

#ifndef _Included_pl_edu_pwr_lab11_Sorting
#define _Included_pl_edu_pwr_lab11_Sorting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_edu_pwr_lab11_Sorting
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_edu_pwr_lab11_Sorting_sort01
        (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     pl_edu_pwr_lab11_Sorting
 * Method:    sort02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_edu_pwr_lab11_Sorting_sort02
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     pl_edu_pwr_lab11_Sorting
 * Method:    sort03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_edu_pwr_lab11_Sorting_sort03
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
